[package]
name = "Icaller"
version = "0.1.0"
authors = ["ChoKyuWon <kyuwoncho18@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

capstone = "0.10.0"
elf = "0.0.10"
goblin = "0.4"
